/**
 * 分类
 * @author 郑业强 2018-12-17 创建文件
 */

#ifndef CA_EVENT_h
#define CA_EVENT_h

#define CATEGORY_BTN_CLICK   @"CATEGORY_BTN_CLICK"        // 添加分类
#define CATEGORY_LONG_GESTURE @"CATEGORY_LONG_GESTURE"    // 长按手势
#define CATEGORY_ACTION_CLICK @"CATEGORY_ACTION_CLICK"    // 删除/添加
#define CATEGORY_ACTION_DELETE_CLICK @"CATEGORY_ACTION_DELETE_CLICK"    // 删除
#define CATEGORY_ACTION_INSERT_CLICK @"CATEGORY_ACTION_INSERT_CLICK"    // 添加
#define CATEGORY_SEG_CHANGE @"CATEGORY_SEG_CHANGE"        // 更改seg

#endif
