/**
 * 通知
 * @author 郑业强 2018-12-24 创建文件
 */

#ifndef LOGIN_NOTIFICATION_h
#define LOGIN_NOTIFICATION_h


#define LOPGIN_FORGET_COMPLETE   @"LOPGIN_FORGET_COMPLETE"    // 忘记密码完成
#define LOPGIN_REGISTER_COMPLETE @"LOPGIN_REGISTER_COMPLETE"  // 注册完成
#define LOPGIN_LOGIN_COMPLETE    @"LOPGIN_LOGIN_COMPLETE"     // 登录完成
#define BIND_PHONE_COMPLETE      @"BIND_PHONE_COMPLETE"       // 绑定手机
#define LOPGIN_LOGOUT_COMPLETE   @"LOPGIN_LOGOUT_COMPLETE"    // 退出登录


#endif
